- alias: 'Turn on Led Power when temp exceeds 23 celsius'
  trigger:
    platform: numeric_state
    entity_id: sensor.dht_sensor_temperature
    above: 23
  action:
    - service: switch.turn_on
      entity_id: switch.led_power_switch

- alias: 'Turn off Led Power when temp drops below 24 celsius'
  trigger:
    platform: numeric_state
    entity_id: sensor.dht_sensor_temperature
    below: 24
  action:
    - service: switch.turn_off
      entity_id: switch.led_power_switch

- alias: 'Time and temp at Altran Foajé'
  trigger:
    - platform: state
      entity_id: input_boolean.run_automation_test
  action:   
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.altran_foaje
        volume: 0.3
        message: "Time is now {{ states.sensor.time.state }} and the temperature inside is {{ states.sensor.temperature.state }} degrees"
        delay: '00:00:15'

- alias: 'Time and temp at play_and_you_di3'
  trigger:
    - platform: state
      entity_id: input_boolean.run_automation_test
  action:   
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.play_and_you_di3
        volume: 0.3
        message: "Time is now {{ states.sensor.time.state }} and the temperature inside is {{ states.sensor.temperature.state }} degrees"
        delay: '00:00:15'

- alias: 'Time and temp at backstrom_boys'
  trigger:
    - platform: state
      entity_id: input_boolean.run_automation_test
  action:   
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.backstrom_boys
        volume: 0.3
        message: "Time is now {{ states.sensor.time.state }} and the temperature inside is {{ states.sensor.temperature.state }} degrees"
        delay: '00:00:15'

- alias: 'Time 2'
  trigger:
    - platform: time
      at: '11:02:00'
  action:
    - service: script.sonos_say
      data:
        sonos_entity: media_player.altran_foaje
        volume: 0.5
        message: 'Time is now 11 02'
        delay: '00:00:15'

- alias: 'Time 1'
  trigger:
    - platform: time
      at: '12:12:00'
  action:
    - service: script.sonos_say
      data:
        sonos_entity: media_player.altran_foaje
        volume: 0.5
        message: 'Time is now 12 12'
        delay: '00:00:15'